modbus:
  ip: "10.0.20.110"
  port: 502
  slave_id: 1
  read_interval: 10  # in seconds

metrics:
  - name: "sungrow_daily_power_yield"
    register: 5003
    type: "U16"
    help: "Current power output in kWh"
    scale: 0.1
  - name: "sungrow_power_yield_total"
    register: 5004
    type: "U32"
    help: "Total power yield in kWh"
  - name: "sungrow_protocol_number"
    register: 4950
    type: "U32"
    help: "Protocol number"
    round: true
  - name: "sungrow_serial_number"
    register: 4990
    type: "U16"
    help: "Serial Number"
  - name: "sungrow_total_running_time_hour"
    register: 5006
    type: "U32"
    help: "Total running time"
  - name: "sungrow_total_export_energy"
    register: 5095
    type: "U32"
    help: "Total export energy"
    scale: 0.1
