{
 "title": "Electricity",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Solar Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sungrow_total_active_power / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_meter_load_power ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daily Generated Power",
   "type": "gauge",
   "description": "Units exported to Grid today",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_daily_power_yield", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daily Export",
   "type": "gauge",
   "description": "Units exported to Grid today",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_daily_export_energy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daily Import",
   "type": "gauge",
   "description": "Units imported from grid today",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_daily_import_energy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Internal Tempreature",
   "type": "gauge",
   "description": "Units exported to Grid today",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_internal_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running Time Today",
   "type": "stat",
   "description": "Total units imported till date",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_daily_running_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_grid_frequency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nominal power",
   "type": "stat",
   "description": "Total units imported till date",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_nominal_active_power", "legendFormat": "__auto" }
   ]
  },
  { "title": "Lifetime Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Lifetime export",
   "type": "stat",
   "description": "Total units exported till date",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_total_export_energy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lifetime generation",
   "type": "stat",
   "description": "Units generated till date",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_power_yield_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total solar usage",
   "type": "stat",
   "description": "Units generated till date",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sungrow_power_yield_total - sungrow_total_export_energy",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total lifetime import",
   "type": "stat",
   "description": "Total units imported till date",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sungrow_total_import_energy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Running Time",
   "type": "stat",
   "description": "Total units imported till date",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sungrow_total_running_time_hour",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Power Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Power generation and Usage (Hourly)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sungrow_total_active_power / 1000",
     "legendFormat": "Solar Generated Power"
    },
    {
     "expr": "sungrow_meter_load_power  / 1000",
     "legendFormat": "Current load"
    },
    {
     "expr": "sungrow_meter_total_power / 1000",
     "legendFormat": "Grid"
    }
   ]
  }
 ]
}